const PODCAST_LINK_NAME = "feedcell";
const PODCAST_LINK_SELECTOR = `.${PODCAST_LINK_NAME}`;
const PODCAST_LIST_HEADER_NAME = "ocseparatorbar";
const PODCAST_LIST_HEADER_SELECTOR = `.${PODCAST_LIST_HEADER_NAME}`;

export default {
  PODCAST_LINK_NAME,
  PODCAST_LINK_SELECTOR,
  PODCAST_LIST_HEADER_NAME,
  PODCAST_LIST_HEADER_SELECTOR,
};
